### ISSUE TITLE
Rename endpoint to /v2/data?

### ISSUE THREAD

**Issue by mauvm** [kukua/concava#26]
@siebrenkranenburg @olliesmeenk Make it configurable? We use devices, stations, sensors interchangeably. Maybe settle on just calling them 'devices'? And therefore rename to `/v1/deviceData`? Or simply `/v1/data`?

**Comment by mauvm** [comment]
`/v2/data` for backwards compatibility.

**Comment by mauvm** [comment]
Resolve #30 first, resulting in an url like `/data`.

Another thing: "data" is ambigious. Use "measurement" instead? E.g. `POST /measurements` and `PUT /devices/{udid}/measurements`?

**Comment by mauvm** [comment]
Options:
- `POST /data` and `PUT /data/{udid}`
- `POST /measurements` and `PUT /measurements/{udid}`
- `POST /payloads` and `PUT /payloads/{udid}`

**Comment by olliesmeenk** [comment]
@mauvm for the general public the endpoint should be configurable just as the selection of the database structure can be. For our own use case we should then configure it to be /v1/deviceData to differentiate it from other data sources. I believe we should use "devices" rather than "sensors" or "stations" for the following reason: A device is a microcontroller (on WDT in this case) with a device ID configured before we receive it. This microcontroller can be switched, but it remains identified by the same ID. The sensors are the individual measuring instruments attached to the device, such as a pressure sensor. Lastly, we should define a station as one specific set of data from all the sensors in one location (station=location bound). If a new device or new sensors are put in the same location, the ID changes but our data consumers will want all the data for that location in one data table.

**Comment by mauvm** [comment]
For now I've decided on both `/measurements` and `/data`. The former out of preference. The latter to allow hosting the [ConCaVa API](kukua.github.io/concava-api/) on the same host: so you can POST binary data to `/data` and JSON data to `/measurements`.

**Comment by mauvm** [comment]
`/sensorData` still works, but will be removed in the future.
